on:
  push:
    branches: [ master ]

name: Deploy to Amazon ECS

jobs:
  deploy-aws:
    name: Deploy/Destroy AWS Infra Prod
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

#     - name: Install aws cli     
#       run: |
#         sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#         sudo unzip awscliv2.zip
#         aws iam list-roles
    - name: Install terraform     
      run: |
        sudo wget https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_linux_amd64.zip
        sudo unzip terraform_1.0.1_linux_amd64.zip
        sudo sudo mv terraform /usr/local/bin/

    - name: Aws Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Terraform Init
      run: |
        cd infra
        terraform init

    - name: Terraform Apply/Destroy
      run: |
        sudo chmod +x apply_destroy_script.sh
        ./apply_destroy_script.sh

  deploy-app:
    name: Deploy App in ECS
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-aws
    env:
      DOCKER_USERNAME: AWS
      AWS_ACCOUNT_ID: "635411703757"
      IMAGE_VERSION: "latest"
      REPOSITORY_NAME: "desafio/app"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Aws Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Build docker image
      run: |
        ls
        sudo docker build -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_VERSION }} .

    - name: Push docker image
      run: |
        PASSWORD=$(sudo aws ecr get-login-password)
        sudo docker login --username ${{ env.DOCKER_USERNAME }} -p $PASSWORD ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        sudo docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_VERSION }}