on:
  push:
    branches: [ dev ]

name: Deploy to Amazon ECS

jobs:
  deploy-aws-dev:
    name: Deploy/Destroy AWS Infra Dev
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCOUNT_REGION: "us-east-1"
      BUCKET: "gama-academy-terraform-state"
      TERRAFORM_VERSION: "1.0.1"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: |
        echo "teste"